# Generated by Django 3.1.14 on 2022-01-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20220108_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='Stamina',
            field=models.IntegerField(default=0),
        ),
    ]
