# Generated by Django 3.1.14 on 2022-01-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20220117_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Element type')),
                ('element_type', models.ManyToManyField(to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
