# Generated by Django 3.1.14 on 2022-01-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_pokemonelementtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='element_type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType'),
        ),
    ]
