# Generated by Django 3.1.14 on 2022-01-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20220119_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='pokemon_entities', verbose_name='Изображение'),
        ),
    ]
